### ISSUE TITLE
Sec. 2.04 Deliverables – Initial Applicant and Recipient Data Matching

### ISSUE THREAD

**Issue by phcheesman** [AlaskaDHSS/RFP-AVS-EVS#17]
There is limited-to-no availability of no-cost financial account information. We would recommend that the State exclude this from your initial data match or modify this section to clarify whether you are willing to pay for financial account information.

**Comment by nfaulknerAK** [comment]
updated section 2.04 (https://github.com/AlaskaDHSS/RFP-AVS-EVS/blob/master/1%20-%20Request%20for%20Proposals.md#sec-204-deliverables)
