### ISSUE TITLE
Sec. 2.05 Requirements – Solution Requirements b. #2

### ISSUE THREAD

**Issue by phcheesman** [AlaskaDHSS/RFP-AVS-EVS#19]
Regarding financial data, we would recommend that State specify that you are not only looking for data from large, national financial institutions but that you also require asset data from 100 percent of Alaska-based financial institutions. If this requirement is not included, the State is likely to end up with a limited asset verification solution that is only comprised of data from the country’s largest financial institutions, rather than including data from the Alaska-based financial institutions where your membership are most likely to bank. Further, the State should require vendors to clarify whether they are providing access to Alaska-based financial institutions as failing to do so will skew the comparison of each vendor’s pricing.

**Comment by nfaulknerAK** [comment]
your comment has been received and we appreciate the feedback.
