### ISSUE TITLE
Sec. 2.05 Requirements – Solution Requirements b. #3

### ISSUE THREAD

**Issue by phcheesman** [AlaskaDHSS/RFP-AVS-EVS#20]
Regarding income data, is the State requiring bi-weekly pay stub-level data (very expensive) or is the State okay with quarterly wage files combined with new hire reports and income estimation data? If the State is requiring bi-weekly pay stub-level data, the State should be aware that currently only a single vendor provides this bi-weekly income data and it the cost is likely to exceed $10 per transaction (more than twice the cost of the rest of any proposed solution). Because of this, the State may want to consider procuring this income data separately and have your asset and eligibility verification services vendor integrate this expensive data into their solution/system. Otherwise, the State will only have a single vendor who is qualified to fulfill the entire scope described by this RFP. If this occurs, the State will be stuck with all of that single vendor’s data, rather than the best data and system available from any vendor. For example, the sole vendor with income data does not necessarily maintain a complete financial asset data source solution nor the best eligibility verification solution nor the best various other data sources which are critical to maintaining a complete EVS.

**Comment by phcheesman** [comment]
Regarding income data, is the State open to the selected vendor obtaining bi-weekly pay stub-level income data (at no cost to the State) from the Federal Data Services Hub, rather than paying a single vendor with this data more than $10 per transaction?

**Comment by nfaulknerAK** [comment]
section 2.05 has been updated.

https://github.com/AlaskaDHSS/RFP-AVS-EVS/blob/master/1%20-%20Request%20for%20Proposals.md#sec-205-requirements
