### ISSUE TITLE
Sec. 4.08 Cost Proposal

### ISSUE THREAD

**Issue by phcheesman** [AlaskaDHSS/RFP-AVS-EVS#21]
We would recommend that the State require vendors to specifically define the following costs:
1.	Implementation fees
2.	Maintenance and operations fees
3.	Per-transaction fees for financial asset verification
4.	Per-transaction fees for income verification 
5.	Per-transaction fees for other eligibility verification checks

This will ensure the State can transparently compare “apples to apples” in evaluating each vendor response. Generically lumping costs together may allow respondents to hide the exclusion of one or more of these high-cost data sources.

**Comment by nfaulknerAK** [comment]
your comment has been received and we appreciate the feedback.
