### ISSUE TITLE
RFP Question

### ISSUE THREAD

**Issue by LNRiskRFP20** [AlaskaDHSS/RFP-AVS-EVS#34]
Jennifer Reed-Poling/LexisNexis Risk Solutions
Sales Executive - State and Local Government Healthcare

 The RFP includes numerous references to identity verification as a required element of service – Section 4.07 Verbal Presentations, makes specific reference to identity “proofing” as a possible presentation element for vendors. Verification typically involves certifying that input identity elements correspond to a “known” identity in the public record (name/social match, identity is not deceased, etc.), while “proofing” typically refers to steps that are taken to certify that the person using that identity is the true owner of the identity.   Can DHHS confirm the requirement of both verification and proofing as part of the procurement and perhaps give an example of how this verification/proofing process will fit within the overall workflow of the eligibility or renewal application process overall?

Thank you for your time.

**Comment by nfaulknerAK** [comment]
Thank you for your question. 

Section 4.07 which currently reads:

“Introductions will be used solely for introducing team member’s names and roles on both the State and vendor teams. Time for introductions will not be allocated to business development purposes. Suggestions for system demonstration may include but not limited to: asset retrieval, income retrieval, identity proofing, data access audit logging, administrative privilege and user management”

Will be updated to read:

Introductions will be used solely for introducing team member’s names and roles on both the State and vendor teams. Time for introductions will not be allocated to business development purposes. Suggestions for system demonstration may include but not limited to: asset retrieval, income retrieval, identity verification, data access audit logging, administrative privilege and user management

**Comment by nfaulknerAK** [comment]
reopening for visibility
