### ISSUE TITLE
Extend question deadline?

### ISSUE THREAD

**Issue by susanjabal** [AlaskaDHSS/RFP-AVS-EVS#36]
## Name and affiliation

Carey Griffen - Equifax

## Section of RFP documents

Section 1.06
 
## Question/Comment

The question deadline is currently 5pm (akst) on Feb 10, 2020. Will the State consider extending the question deadline?

**Comment by tracymack** [comment]
Thank you for your question.

Section 1.06 has been changed from "Questions or comments regarding this RFP shall be submitted as issues within this RFP's GitHub repository no later than 5:00 PM (Alaska Standard Time) on Monday, February 10, 2020" to "Questions or comments regarding this RFP shall be submitted as issues within this RFP's GitHub repository no later than 5:00 PM (Alaska Standard Time) on Monday, February 11, 2020"

Section 1.12 has been changed from "Deadline for receipt of questions on February 10, 2020" to "Deadline for receipt of questions on February 11, 2020"

**Comment by tracymack** [comment]
Pull request #38

**Comment by tracymack** [comment]
Also updated README via pull request #45
