### ISSUE TITLE
Question re: Associated Systems

### ISSUE THREAD

**Issue by susanjabal** [AlaskaDHSS/RFP-AVS-EVS#42]
CJIS Group, LLC

General Question:
Which other systems will have to integrate/interface with the Asset Verification System (AVS)/Enhanced Verification System (EVS), and will the Department provide incumbent vendors for each system?

**Comment by nfaulknerAK** [comment]
Our preference is for the AVS/EVS system to be a stand alone portal where eligibility staff will look up client information. We also have requested that bidders explain their capability to integrate their solutions into other systems as eventually we would incorporate the services into our existing eligibility systems.
