### ISSUE TITLE
Question re: Anticipated Users

### ISSUE THREAD

**Issue by susanjabal** [AlaskaDHSS/RFP-AVS-EVS#43]
CJIS Group, LLC

General Question:
What is the number of users anticipated for the Asset Verification System (AVS)/Enhanced Verification System (EVS)?

**Comment by nfaulknerAK** [comment]
We do not have an expected unique user count. Information regarding the number of anticipated applicant/client data requests can be found in the RFP [section 2.03](https://github.com/AlaskaDHSS/RFP-AVS-EVS/blob/master/1%20-%20Request%20for%20Proposals.md#sec-203-scope-of-work)
