### ISSUE TITLE
‘AVS Required Vendor Response - DHSS IT Requirements’

### ISSUE THREAD

**Issue by phcheesman** [AlaskaDHSS/RFP-AVS-EVS#46]
## Name and affiliation

Peter Cheesman, Public Consulting Group, Inc.

## Section of RFP documents

1.04
 
## Question/Comment

The State has identified ‘AVS Required Vendor Response - DHSS IT Requirements’ as a required document. However this document does not appear to be included within this RFP GitHub.

**Comment by susanjabal** [comment]
The 2nd attachment included in the repository is titled: '2 - Required Vendor Response - DHSS IT Requirements.pdf'. 
This document is the same as the one identified in the RFP as 'AVS Required Vendor Response - DHSS IT Requirements’.
This is the correct document, and is required in response to this RFP.
